export const LATEX_CATALOG: Array<{ name: string; description: string }> = [
  { name: 'amsmath', description: 'Fórmulas matemáticas avançadas' },
  { name: 'amssymb', description: 'Símbolos matemáticos extras' },
  { name: 'graphicx', description: 'Inclusão de imagens' },
  { name: 'hyperref', description: 'Links e PDF navegável' },
  { name: 'geometry', description: 'Margens e tamanho da página' },
  { name: 'babel', description: 'Idioma e hifenização' },
  { name: 'inputenc', description: 'Codificação de entrada (UTF-8)' },
  { name: 'fontenc', description: 'Codificação de fontes (T1)' },
  { name: 'biblatex', description: 'Bibliografia moderna' },
  { name: 'natbib', description: 'Citações autor-ano' },
  { name: 'booktabs', description: 'Tabelas com linhas profissionais' },
  { name: 'xcolor', description: 'Cores' },
  { name: 'tikz', description: 'Desenhos e diagramas' },
  { name: 'pgfplots', description: 'Gráficos de dados' },
  { name: 'listings', description: 'Código-fonte formatado' },
  { name: 'minted', description: 'Código com realce (requer shell-escape)' },
  { name: 'siunitx', description: 'Números e unidades SI' },
  { name: 'cleveref', description: 'Referências cruzadas inteligentes' },
  { name: 'caption', description: 'Legendas personalizadas' },
  { name: 'subcaption', description: 'Subfiguras e subtabelas' },
  { name: 'float', description: 'Posicionamento de flutuantes (H)' },
  { name: 'enumitem', description: 'Listas personalizadas' },
  { name: 'microtype', description: 'Refinamento tipográfico' },
  { name: 'lmodern', description: 'Fontes Latin Modern' },
  { name: 'csquotes', description: 'Aspas contextuais' },
  { name: 'url', description: 'Quebra de URLs' },
  { name: 'fancyhdr', description: 'Cabeçalhos e rodapés' },
  { name: 'titlesec', description: 'Formatação de títulos de seção' },
  { name: 'tocloft', description: 'Formatação do sumário' },
  { name: 'multirow', description: 'Células mescladas em linhas' },
  { name: 'longtable', description: 'Tabelas em várias páginas' },
  { name: 'array', description: 'Extensões de colunas de tabela' },
  { name: 'tabularx', description: 'Tabelas com largura fixa' },
  { name: 'algorithm2e', description: 'Algoritmos em pseudocódigo' },
  { name: 'algorithmicx', description: 'Algoritmos em pseudocódigo (estilo layout)' },
  { name: 'mathtools', description: 'Extensões do amsmath' },
  { name: 'bm', description: 'Símbolos matemáticos em negrito' },
  { name: 'physics', description: 'Notação de física' },
  { name: 'chemfig', description: 'Estruturas químicas' },
  { name: 'todonotes', description: 'Notas de pendências' },
  { name: 'lipsum', description: 'Texto de exemplo' },
  { name: 'setspace', description: 'Espaçamento entre linhas' },
  { name: 'parskip', description: 'Parágrafos sem recuo, com espaço' },
  { name: 'indentfirst', description: 'Recuo no primeiro parágrafo' },
  { name: 'appendix', description: 'Apêndices' },
  { name: 'glossaries', description: 'Glossário e siglas' },
  { name: 'acronym', description: 'Lista de siglas' },
  { name: 'nomencl', description: 'Lista de símbolos' },
  { name: 'pdfpages', description: 'Inclusão de páginas de PDF' },
  { name: 'wrapfig', description: 'Texto contornando figuras' },
  { name: 'placeins', description: 'Barreiras para flutuantes' },
  { name: 'afterpage', description: 'Comandos após a página atual' },
  { name: 'lastpage', description: 'Referência à última página' },
  { name: 'datetime2', description: 'Datas e horas formatadas' },
  { name: 'xspace', description: 'Espaço automático em macros' },
  { name: 'etoolbox', description: 'Ferramentas de programação' },
  { name: 'ifthen', description: 'Condicionais simples' },
  { name: 'calc', description: 'Aritmética em comprimentos' },
  { name: 'soul', description: 'Sublinhado e destaque' },
  { name: 'ulem', description: 'Sublinhado com quebra de linha' },
];
