import { describe, expect, it } from 'vitest';
import { parseManifest, renderPackagesTex } from './package-manifest';

describe('renderPackagesTex', () => {
  it('orders by order and comments out disabled packages', () => {
    const tex = renderPackagesTex([
      { name: 'hyperref', enabled: true, order: 3 },
      { name: 'tikz', enabled: false, order: 2 },
      { name: 'inputenc', options: 'utf8', enabled: true, order: 1 },
    ]);
    expect(tex).toBe(
      [
        '% Generated by latex-studio from latex-packages.json. Edit the manifest, not this file.',
        '\\usepackage[utf8]{inputenc}',
        '% disabled: \\usepackage{tikz}',
        '\\usepackage{hyperref}',
        '',
      ].join('\n'),
    );
  });
});

describe('parseManifest', () => {
  it('accepts a valid manifest', () => {
    const json = '[{"name":"amsmath","enabled":true,"order":1}]';
    expect(parseManifest(json)).toHaveLength(1);
  });

  it('rejects invalid shapes with a clear message', () => {
    expect(() => parseManifest('{}')).toThrow('expected an array');
    expect(() => parseManifest('[{"name":"","enabled":true,"order":1}]')).toThrow('entry 0');
    expect(() => parseManifest('[{"name":"a","enabled":"yes","order":1}]')).toThrow('enabled');
  });
});
