import { describe, expect, it } from 'vitest';
import { parseManifest, renderPackagesTex } from './package-manifest';

describe('renderPackagesTex', () => {
  it('orders by order and bypasses disabled packages', () => {
    const tex = renderPackagesTex([
      { name: 'hyperref', enabled: true, order: 3 },
      { name: 'tikz', enabled: false, order: 2 },
      { name: 'inputenc', options: 'utf8', enabled: true, order: 1 },
    ]);
    expect(tex).toBe(
      [
        '% Generated by latex-studio from latex-packages.json. Edit the manifest, not this file.',
        '\\usepackage[utf8]{inputenc}',
        '% disabled: tikz (bypass: later \\usepackage{tikz} lines are skipped)',
        '\\expandafter\\def\\csname ver@tikz.sty\\endcsname{0000/00/00}',
        '\\usepackage{hyperref}',
        '',
      ].join('\n'),
    );
  });
});

describe('renderPackagesTex bypass', () => {
  it('defines ver@ and the deduped opt@ union for a disabled used package', () => {
    const tex = renderPackagesTex(
      [{ name: 'hyperref', enabled: false, order: 0 }],
      [
        { name: 'hyperref', options: 'colorlinks, urlcolor=blue' },
        { name: 'hyperref', options: 'colorlinks' },
        { name: 'other', options: 'x' },
      ],
    );
    expect(tex).toContain('\\expandafter\\def\\csname ver@hyperref.sty\\endcsname{0000/00/00}');
    expect(tex).toContain(
      '\\expandafter\\def\\csname opt@hyperref.sty\\endcsname{colorlinks,urlcolor=blue}',
    );
    expect(tex).not.toContain('other');
    const braces = renderPackagesTex(
      [{ name: 'p', enabled: false, order: 0 }],
      [
        { name: 'p', options: 'a={x,y}' },
        { name: 'p', options: 'b=#1' },
      ],
    );
    expect(braces).not.toContain('opt@');
    const ok = renderPackagesTex(
      [{ name: 'p', enabled: false, order: 0 }],
      [{ name: 'p', options: 'a={x,y}, c' }],
    );
    expect(ok).toContain('opt@p.sty\\endcsname{a={x,y},c}');
  });

  it('keeps the usepackage line when enabled', () => {
    const tex = renderPackagesTex(
      [
        { name: 'a', options: 'x', enabled: true, order: 0 },
        { name: 'b', enabled: true, order: 1 },
      ],
      [{ name: 'a', options: 'y' }],
    );
    // `a` is still loaded by the source: not repeated (it would clash on options).
    expect(tex).toContain('% enabled: a (loaded by the source)');
    expect(tex).not.toContain('\\usepackage[x]{a}');
    expect(tex).toContain('\\usepackage{b}');
    expect(tex).not.toContain('ver@');
  });
});

describe('parseManifest', () => {
  it('accepts a valid manifest', () => {
    const json = '[{"name":"amsmath","enabled":true,"order":1}]';
    expect(parseManifest(json)).toHaveLength(1);
  });

  it('rejects invalid shapes with a clear message', () => {
    expect(() => parseManifest('{}')).toThrow('expected an array');
    expect(() => parseManifest('[{"name":"","enabled":true,"order":1}]')).toThrow('entry 0');
    expect(() => parseManifest('[{"name":"a","enabled":"yes","order":1}]')).toThrow('enabled');
  });
});
