export type PackageEntry = {
  name: string;
  options?: string;
  enabled: boolean;
  order: number;
};

export type PackageManifest = PackageEntry[];

const HEADER =
  '% Generated by latex-studio from latex-packages.json. Edit the manifest, not this file.';

const usepackage = (e: PackageEntry) =>
  `\\usepackage${e.options ? `[${e.options}]` : ''}{${e.name}}`;

export function renderPackagesTex(manifest: PackageManifest): string {
  const lines = [...manifest]
    .sort((a, b) => a.order - b.order)
    .map((e) => (e.enabled ? usepackage(e) : `% disabled: ${usepackage(e)}`));
  return `${[HEADER, ...lines].join('\n')}\n`;
}

export function parseManifest(json: string): PackageManifest {
  let data: unknown;
  try {
    data = JSON.parse(json);
  } catch {
    throw new Error('Invalid package manifest: not valid JSON');
  }
  if (!Array.isArray(data)) {
    throw new Error('Invalid package manifest: expected an array');
  }
  data.forEach((e, i) => {
    const at = `Invalid package manifest: entry ${i}`;
    if (typeof e !== 'object' || e === null) throw new Error(`${at} must be an object`);
    if (typeof e.name !== 'string' || !/^[A-Za-z0-9._-]+$/.test(e.name)) {
      throw new Error(`${at} needs a valid package "name"`);
    }
    if (typeof e.enabled !== 'boolean') throw new Error(`${at} needs a boolean "enabled"`);
    if (typeof e.order !== 'number') throw new Error(`${at} needs a numeric "order"`);
  });
  return data as PackageManifest;
}
