export type PackageEntry = {
  name: string;
  options?: string;
  enabled: boolean;
  order: number;
};

export type PackageManifest = PackageEntry[];

const HEADER =
  '% Generated by latex-studio from latex-packages.json. Edit the manifest, not this file.';

const usepackage = (e: PackageEntry) =>
  `\\usepackage${e.options ? `[${e.options}]` : ''}{${e.name}}`;

export type PackageUsage = { name: string; options?: string };

// Defining \ver@<name>.sty makes LaTeX skip any later \usepackage/\RequirePackage of it;
// \opt@<name>.sty pre-seeds the options so the skipped call can't raise "Option clash".
/** Splits `a,b={c,d}` at top-level commas only. */
function splitOptions(s: string): string[] {
  const out: string[] = [];
  let depth = 0;
  let cur = '';
  for (const ch of s) {
    if (ch === ',' && depth === 0) {
      out.push(cur);
      cur = '';
      continue;
    }
    if (ch === '{') depth++;
    if (ch === '}') depth--;
    cur += ch;
  }
  out.push(cur);
  return out.map((o) => o.trim()).filter(Boolean);
}

function bypass(e: PackageEntry, usage: PackageUsage[]): string[] {
  const opts = [
    ...new Set(
      usage.filter((u) => u.name === e.name).flatMap((u) => splitOptions(u.options ?? '')),
    ),
  ].join(',');
  // An unbalanced brace or a `#` inside \def would swallow the rest of the preamble.
  const depth = [...opts].reduce(
    (d, c) => (d < 0 ? d : c === '{' ? d + 1 : c === '}' ? d - 1 : d),
    0,
  );
  const safe = opts && depth === 0 && !opts.includes('#');
  return [
    `% disabled: ${e.name} (bypass: later \\usepackage{${e.name}} lines are skipped)`,
    `\\expandafter\\def\\csname ver@${e.name}.sty\\endcsname{0000/00/00}`,
    ...(safe ? [`\\expandafter\\def\\csname opt@${e.name}.sty\\endcsname{${opts}}`] : []),
  ];
}

export function renderPackagesTex(manifest: PackageManifest, usage: PackageUsage[] = []): string {
  const used = (e: PackageEntry) => usage.some((u) => u.name === e.name);
  const lines = [...manifest]
    .sort((a, b) => a.order - b.order)
    .flatMap((e) => {
      if (!e.enabled) return bypass(e, usage);
      // Still loaded by the source itself: a second \usepackage would raise "Option clash".
      if (used(e)) return [`% enabled: ${e.name} (loaded by the source)`];
      return [usepackage(e)];
    });
  return `${[HEADER, ...lines].join('\n')}\n`;
}

export function parseManifest(json: string): PackageManifest {
  let data: unknown;
  try {
    data = JSON.parse(json);
  } catch {
    throw new Error('Invalid package manifest: not valid JSON');
  }
  if (!Array.isArray(data)) {
    throw new Error('Invalid package manifest: expected an array');
  }
  data.forEach((e, i) => {
    const at = `Invalid package manifest: entry ${i}`;
    if (typeof e !== 'object' || e === null) throw new Error(`${at} must be an object`);
    if (typeof e.name !== 'string' || !/^[A-Za-z0-9._-]+$/.test(e.name)) {
      throw new Error(`${at} needs a valid package "name"`);
    }
    if (typeof e.enabled !== 'boolean') throw new Error(`${at} needs a boolean "enabled"`);
    if (typeof e.order !== 'number') throw new Error(`${at} needs a numeric "order"`);
  });
  return data as PackageManifest;
}
