import type { Project, ProjectEngine, ProjectRole, ProjectWithRole } from './project';

export const PROJECT_REPOSITORY = Symbol('PROJECT_REPOSITORY');

export interface NewProject {
  /** Generated by the caller, so the repository directory is filled before the row exists. */
  id: string;
  name: string;
  mainFile?: string;
  engine?: ProjectEngine;
}

export type ProjectPatch = Partial<Pick<Project, 'engine' | 'mainFile'>>;

export interface Member {
  userId: string;
  name: string;
  email: string;
  role: ProjectRole;
}

export interface ProjectRepository {
  listMembers(projectId: string): Promise<Member[]>;
  /** Inserts or updates the membership. */
  setMember(projectId: string, userId: string, role: ProjectRole): Promise<void>;
  removeMember(projectId: string, userId: string): Promise<void>;
  /** Inserts the project and its owner membership in one transaction. */
  create(project: NewProject, ownerId: string): Promise<Project>;
  findById(id: string): Promise<Project | null>;
  update(id: string, patch: ProjectPatch): Promise<Project>;
  /** Newest first. */
  listForUser(userId: string): Promise<ProjectWithRole[]>;
  roleOf(projectId: string, userId: string): Promise<ProjectRole | null>;
  /** Projects owned by the user. */
  countForUser(userId: string): Promise<number>;
  delete(id: string): Promise<void>;
  /** Flags uncommitted collaborative edits for autocommit; keeps the first timestamp. */
  markDirty(id: string): Promise<void>;
  /** Remembers who edited a file collaboratively, so the autosave is committed in their name. */
  recordEdit(projectId: string, path: string, userId: string): Promise<void>;
}
