import type { Project, ProjectEngine, ProjectRole, ProjectWithRole } from './project';

export const PROJECT_REPOSITORY = Symbol('PROJECT_REPOSITORY');

export interface NewProject {
  /** Generated by the caller, so the repository directory is filled before the row exists. */
  id: string;
  name: string;
  mainFile?: string;
  engine?: ProjectEngine;
}

export type ProjectPatch = Partial<Pick<Project, 'engine' | 'mainFile'>>;

export type ProjectListFilter = 'all' | 'mine' | 'shared';

export interface ProjectListCursor {
  updatedAt: string;
  id: string;
}

export interface ProjectListOptions {
  limit: number;
  filter: ProjectListFilter;
  search: string;
  cursor: ProjectListCursor | null;
}

export interface ProjectListPage {
  items: ProjectWithRole[];
  total: number;
  next: ProjectListCursor | null;
}

export interface Member {
  userId: string;
  name: string;
  email: string;
  role: ProjectRole;
}

export interface ProjectRepository {
  listMembers(projectId: string): Promise<Member[]>;
  /** Inserts or updates the membership. */
  setMember(projectId: string, userId: string, role: ProjectRole): Promise<void>;
  removeMember(projectId: string, userId: string): Promise<void>;
  /** Inserts the project and its owner membership in one transaction. */
  create(project: NewProject, ownerId: string): Promise<Project>;
  findById(id: string): Promise<Project | null>;
  update(id: string, patch: ProjectPatch): Promise<Project>;
  /** Stable keyset order: last modification descending, then ID descending. */
  listPageForUser(userId: string, options: ProjectListOptions): Promise<ProjectListPage>;
  roleOf(projectId: string, userId: string): Promise<ProjectRole | null>;
  /** Projects owned by the user. */
  countForUser(userId: string): Promise<number>;
  delete(id: string): Promise<void>;
  /** Remembers who edited a file collaboratively, so the next commit of it names them. */
  recordEdit(projectId: string, path: string, userId: string): Promise<void>;
  /**
   * Runs `commit` with who edited `paths` (every file when null), then clears those records, so
   * each edit is credited once. A `commit` that throws clears nothing; edits recorded while it
   * runs stay for the next commit.
   */
  withEditors<T>(
    projectId: string,
    paths: string[] | null,
    commit: (editors: Array<{ name: string; email: string }>) => Promise<T>,
  ): Promise<T>;
}
